// Write src/palette-names.ts: each palette emoji's Unicode name and group (from unicode-emoji-json), compact enough for
// a browser to search the palette by name and show it by group; and src/palette-keywords.ts: its emojilib keywords,
// which Jev's options are drawn by (server only). Run after the palette changes:
//   npm run palette-names -w @cw/emoji
import { writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { PALETTE } from '../src/canvas.ts'

const data = createRequire(import.meta.url)('unicode-emoji-json/data-by-emoji.json') as Record<string, { name: string; group: string }>
const bare = (e: string) => e.replace(/️/g, '')
const byBare = new Map(Object.entries(data).map(([k, v]) => [bare(k), v]))
const info = (e: string) => data[e] ?? byBare.get(bare(e))
const groups = [...new Set(PALETTE.map((e) => info(e)?.group ?? 'Symbols'))]
const rows = PALETTE.map((e) => [e, info(e)?.name ?? 'emoji', groups.indexOf(info(e)?.group ?? 'Symbols')] as const)
writeFileSync(new URL('../src/palette-names.ts', import.meta.url), `// Generated by scripts/palette-names.ts from unicode-emoji-json: [emoji, Unicode name, group index] for the palette.
export const GROUPS = ${JSON.stringify(groups)} as const
export const NAMES: readonly (readonly [string, string, number])[] = ${JSON.stringify(rows)}
`)
console.log(`✓ src/palette-names.ts: ${rows.length} emoji in ${groups.length} groups`)

// words on more than COMMON emoji (flag, face, nature…) join everything to everything, so they are left out
const COMMON = 40
const lib = createRequire(import.meta.url)('emojilib') as Record<string, string[]>
const libBare = new Map(Object.entries(lib).map(([k, v]) => [bare(k), v]))
const wordsOf = (e: string) => [...new Set((lib[e] ?? libBare.get(bare(e)) ?? []).flatMap((k) => k.toLowerCase().split(/[_\s]+/)).filter((w) => w.length > 2 && w !== 'with' && w !== 'and'))]
const df = new Map<string, number>()
for (const e of PALETTE) for (const w of wordsOf(e)) df.set(w, (df.get(w) ?? 0) + 1)
const keywords = Object.fromEntries(PALETTE.map((e) => [e, wordsOf(e).filter((w) => df.get(w)! > 1 && df.get(w)! <= COMMON).join(' ')]))
writeFileSync(new URL('../src/palette-keywords.ts', import.meta.url), `// Generated by scripts/palette-names.ts from emojilib: each palette emoji's keywords, the common ones left out.
export const KEYWORDS: Readonly<Record<string, string>> = ${JSON.stringify(keywords)}
`)
console.log(`✓ src/palette-keywords.ts: ${Object.values(keywords).filter(Boolean).length} emoji with keywords`)
