// Write src/palette-names.ts: each palette emoji's Unicode name and group (from unicode-emoji-json), compact enough for
// a browser to search the palette by name and show it by group. Run after the palette changes:
//   npm run palette-names -w @cw/emoji
import { writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { PALETTE } from '../src/canvas.ts'

const data = createRequire(import.meta.url)('unicode-emoji-json/data-by-emoji.json') as Record<string, { name: string; group: string }>
const bare = (e: string) => e.replace(/️/g, '')
const byBare = new Map(Object.entries(data).map(([k, v]) => [bare(k), v]))
const info = (e: string) => data[e] ?? byBare.get(bare(e))
const groups = [...new Set(PALETTE.map((e) => info(e)?.group ?? 'Symbols'))]
const rows = PALETTE.map((e) => [e, info(e)?.name ?? 'emoji', groups.indexOf(info(e)?.group ?? 'Symbols')] as const)
writeFileSync(new URL('../src/palette-names.ts', import.meta.url), `// Generated by scripts/palette-names.ts from unicode-emoji-json: [emoji, Unicode name, group index] for the palette.
export const GROUPS = ${JSON.stringify(groups)} as const
export const NAMES: readonly (readonly [string, string, number])[] = ${JSON.stringify(rows)}
`)
console.log(`✓ src/palette-names.ts: ${rows.length} emoji in ${groups.length} groups`)
